### ISSUE TITLE
[REQUEST]: Suppress GPU Usage when not used 

### ISSUE THREAD

**Issue by MagicalNET** [deiteris/voice-changer#169]
### In a few words, describe your idea

When not converting voice, suppress the GPU usage. This way GPU only becomes used when needed, saving resources. Though not sure if it'll cause artifacts doing so, a toggle should be fine if possible.

**Comment by deiteris** [comment]
Hi @MagicalNET! 

Just for the context, the behavior you are requesting was in versions before [b2271](https://github.com/deiteris/voice-changer/releases/tag/b2271). When the audio was silent, GPU was not utilized with those versions. However, in most cases, it caused NVIDIA GPUs to go into power saving mode between the moments of silence and causing big lag/unstable latency when you start speaking again. So recent versions have "busy wait" to keep GPU always on and ready to respond instantly at the cost of constant GPU usage.

I can consider bringing an option to toggle "busy wait" (which would be on by default), somehow it's not a problem for AMD GPUs for example. But I would not recommend disabling it for NVIDIA users at least.

**Comment by MagicalNET** [comment]
I see, wouldn't setting GPU power performance to max via the Nvidia control panel remedy this solution as in going power saving mode? I used the original version of this and worked fine and haven't really had any issues with it (personally).

**Comment by deiteris** [comment]
I believe that it may be not noticeable sometimes because I had similar experience 🙂 I have a laptop with GTX 1650 that I use for testing and have max performance set in Nvidia control panel. I can say that it's still a gamble and I can even demonstrate this with GPU-Z if you want (or you can see it for yourself as well). Sometimes it drops the clocks to 0/200mhz (core/memory) when idling and it would lag when going back to nominal clocks. Sometimes it decides to "fix" memory clock to 1500mhz (even after I close the voice changer) even when idling and work just fine.

I haven't tested 1650 thoroughly with original v1, but I could double-check this as well. Maybe it uses a bit more GPU even when idling and this keeps the GPU from dropping the clocks.

**Comment by MagicalNET** [comment]
Little unrelated, but seems like a bug with latest build? Not sure. I'm using chunk 117ms, 2.7s extra and keeps spiking from 38% gpu to 87% every so often. Though playing a video on youtube or game along side it seems to lower the usage and prevent it from spiking that hard. Is this normal or?

**Comment by deiteris** [comment]
That's usually normal when only voice changer is running. If you also see that the core/memory frequency fluctuates, then it's a correct behavior currently. Which GPU do you have?

**Comment by MagicalNET** [comment]
I have a 2080
