### ISSUE TITLE
[REQUEST]: Connecting to another machine (server)

### ISSUE THREAD

**Issue by MagicalNET** [deiteris/voice-changer#180]
### In a few words, describe your idea

Connecting to secondary machines or virtual machines

### More information

It would be nice to have an option to host this on IP: 0.0.0.0, or 192.168.x.x. That way I can utilize Virtual Servers or secondary machines in my house as an host. Not sure if possible already.

**Comment by crichu894** [comment]
I'd like to be able to use the VoiceChanger I have on my PC when I'm away from home. I tried running it from the source code, installing the dependencies, and it works just as well as the precompiled version. I tried modifying the following files:

- voice-changer\server\main.py
- voice-changer\server\settings.py
- voice-changer\server\mods\origins.py

I replaced the lines that have 127.0.0.1 with 0.0.0.0 so that it listens on all interfaces. However, even though I have the ports and DDNS configured correctly, it only works on 127.0.0.1.

I really hope this feature can be implemented. It would be very useful, for example, to run more than one remote instance of VoiceChanger if the GPU and available hardware resources support it. Oh, I'd be so happy!

**Comment by deiteris** [comment]
Hi @crichu894, @MagicalNET,

Actually you can, though it's currently undocumented since it's rarely used, but Kaggle and Colab use this method. What you can do is to create a file named `.env` near `MMVCServerSIO.exe` and specify the following settings:
```
# The interface to listen to. You can specify either 0.0.0.0 to listen on all interfaces or an address of specific interface.
HOST='<ip_address>' 
# The origin must be a valid URL! I.e. https://192.168.0.1:18888. Multiple values may be specified if you want to have access from several origins. Your local host (127.0.0.1:18888) is allowed by default.
ALLOWED_ORIGINS='["https://<ip_address>:<port>"]'
# In case you may want to also change the port, there's an option for it too.
PORT='18888'
```

To start the voice changer in HTTPS mode, you can create a batch file that will run the voice changer without opening the browser and in HTTPS mode:
```
@echo off
MMVCServerSIO.exe --launch-browser false --https true
pause
```

After it starts, you should be able to open the link. For example, if you specified `HOST=192.168.0.1` and `ALLOWED_ORIGINS='["https://192.168.0.1:18888"]'`), you should be able to open https://192.168.0.1:18888 in your browser and use the voice changer UI from other machines in your local network.

In case you might wonder why it is a bit more complicated than in the original, it is because of the security. Here it is restricted to 127.0.0.1 by default. The original version listens (or at least used to listen) on 0.0.0.0 by default so anyone on your network could connect. It also allowed connections from any origin, so you could visit a web page that could potentially communicate with your voice changer and make possibly malicious requests.

**Comment by MagicalNET** [comment]
I like more advanced settings like this, its good and not as sloppy like the original. Thanks for this, I'll give it a test.

**Comment by PlueRyvius** [comment]
For clarification on this:
HOST='<ip_address>' 
This would be set at the IP of the computer running the server?

ALLOWED_ORIGINS='["https://<ip_address>:<port>"]'
While this should be set to the computer trying to connect remotely? 

Should there be an indication in the log file that shows when this changes? A change from 

[main] The server is listening on https://127.0.0.1:18888/

**Comment by MagicalNET** [comment]
https://rentry.co/ForkVoiceChangerGuide

You can find more information how to do it here.

**Comment by WanderingYouth** [comment]
Pardon me. I recently set up one of my older laptops to run a RVC server. It's a fresh install of Windows 10, and right after setting everything up it gives me this error. 

"ERROR:    [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "shutil.py", line 633, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MINIPC~1\\AppData\\Local\\Temp\\tmp9hd0d9xb\\tmp_dir\\in.wav'"

I assume it doesn't have permission or something is blocking it?

**Comment by blearner2525** [comment]
sorry to necro this post as i just recently saw this . i have tried and got it working and connected to my second pc , however i am unable to select my mic which is on my first pc. any advice is appreciated. thank you
